### ISSUE TITLE
AMD graphics card driver may need to be updated

### ISSUE THREAD

**Issue by shangren-cmd** [AlexxandreFS/Batocera.PLUS#207]
The AMD RX580 4G has good graphics on the original Batocera, V33, V34V35V36V37, but tears on the PLUS screen

**Comment by asleyvm** [comment]
A problem was found in the driver, can you test this image and let me know if it worked?
we don't have this model board for testing

https://drive.google.com/file/d/1NdQAHIq9gTpyfPp0b2LHXjGNwNonVa80

**Comment by shangren-cmd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by AlexxandreFS** [comment]
This should fix the problem ab02ab1feb769cbb4ef8c99242b5e4db942068ff

**Comment by shangren-cmd** [comment]
Okay, thank you for bringing us such a great system, and thank you for taking my submission seriously
